-- Проверка структуры базы данных
USE HabitTrackerDb1;

-- Проверка таблицы Users
PRINT 'Users table:';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' ORDER BY ORDINAL_POSITION;

-- Проверка таблицы Categories
PRINT 'Categories table:';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Categories' ORDER BY ORDINAL_POSITION;

-- Проверка таблицы Habits
PRINT 'Habits table:';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Habits' ORDER BY ORDINAL_POSITION;

-- Проверка таблицы HabitLogs
PRINT 'HabitLogs table:';
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'HabitLogs' ORDER BY ORDINAL_POSITION;
